### ISSUE TITLE
Why based on jQuery?

### ISSUE THREAD

**Issue by antonholmquist** [cloudinary/cloudinary_js#52] opened 2015-06-21 15:03 UTC
Basing this library on jQuery has the big disadvantage of making it difficult to use on the server side in nodejs. Also, the nodejs library is not possible to run in the browser due to the use of node-only modules such as fs.

To me, it's not really clear why the jQuery requirement is needed?

A vanilla javascript library instead of one strict client-side and one strict server-side would be awesome.

**Comment by tocker** [comment] 2015-06-28 11:13
Duplicate of #38. 

We are working on a jQuery-free version for the browser side.
The [NodeJS Cloudinary SDK](https://github.com/cloudinary/cloudinary_npm) includes code that is only relevant to the server side.
Mixing them together would create an unnecessarily bloated code - where we are actually trying to reduce the size of client side JS.

**Closed by tocker** 2015-06-28 11:13 UTC
Labels: duplicate
