### ISSUE TITLE
Is "_" needed from lodash? 

### ISSUE THREAD

**Issue by lostboy** [cloudinary/cloudinary_js#114] opened 2016-12-18 05:01 UTC
I could be getting this wrong but requiring `_` from lodash brings in the whole library which is pretty huge. Would it be possible to just import the utilities you need? When I analyse my webpack build lodash is responsible for 688kb (uncompressed) which becomes the largest dependency I have. Thoughts?

**Comment by nadavofi** [comment] 2016-12-18 15:44
When you don't need the entire lodash library on your application, you can use the shrinkwrap cloudinary-core version instead. For more information see: https://github.com/cloudinary/pkg-cloudinary-core#installation or the upload inclusive version: https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload

**Comment by yoadsn** [comment] 2017-01-10 14:25
@nadavofi - Thanks for the info.
> you can use the shrinkwrap cloudinary-core version instead
IS that available as an NPM package? So far I can only find the cloudinary-core package which pull in the entire lodash package.
The link you point at describes the shrinkwrap with bower - using webpack or browserify we rely on NPM packages to deliver dependencies..

Thanks!

**Comment by yoadsn** [comment] 2017-01-10 14:32
Ok, I see the shrinkwrap is included with the cloudinary-core package.
Importing it with something like
'require('cloudinary-core/cloudinary-core-shrinkwrap.js');'
Seems to work - was that your intention? I think this could be better documented if so..

**Comment by nadavofi** [comment] 2017-01-12 11:10
Thanks for your feedback, Yoad.
We are about to release a new documentation for Javascript very soon.

**Comment by ignatiusreza** [comment] 2017-11-22 09:48
Hi there,

I think the solution suggested above is sub-optimal.. even though using shrinkwrap does avoid including all of lodash, it also mean that cloudinary-core will hold it's own version of lodash.. and if the application is also using lodash, it will hold some duplications.. it also makes using `cloudinary-react` a bit more cumbersome, since that package use the non--shrinkwrap version of `cloudinary-core`..

**Comment by roeeba** [comment] 2017-11-26 12:21
Hi @ignatiusreza. Note that if the application is using lodash elsewhere, then you can use core and no duplication occurs.

In addition, the shrinkwrap includes a subset of the lodash library - not the whole thing.

To use the shrinkwrap version instead of core + lodash, add the following to your webpack configuration:

```
  resolve: {
    alias: {
      "cloudinary-core": "cloudinary-core/cloudinary-core-shrinkwrap" 
    }
  }
```

It will make the application use the shrinkwrap version and the generic lodash library will not be loaded.

**Comment by ignatiusreza** [comment] 2017-11-27 02:35
Hi @roeeba, I'm aware of those, but it still doesn't change the fact that since `cloudinary-core` `import "lodash"`, the full lodash is imported even though both cloudinary, and the application might only use a subset of it.. to better visualize the issue, I've made a small repro project https://github.com/ignatiusreza/cloudinary-114 ..

In it, you'll see 4 commits, please compare how `dist/report.html` (generated via `webpack-bundle-analyzer`) changed with each commits:

1. initialize the project, and add a simple application where lodash is imported via `import _ from "lodash"`.. notice that the full lodash library is included in the output bundle..

2. optimize by changing the import to be selective via `import isEmpty from "lodash/isEmpty"`.. and bundle analyzer reflect these by showing that now, only a small subset of lodash is included in the output bundle..

3. add `import cloudinary from "cloudinary-core"` .. and then on top of the selective import added by step 2, the full lodash library is now back into the bundle.. which actually does include duplicates..

4. add the `resolve.alias` config, which does help reduce the bundle size, but now `cloudinary-core-shrinkwrap` include its own copy of lodash separate from the rest of the application..

**Comment by roeeba** [comment] 2017-12-03 15:38
Hi @ignatiusreza. In your example, the duplication results in about 1800 extra bytes. Indeed, if the app uses a subset of lodash itself there will be some duplication.

To optimize the application in your case, you should build a subset of lodash based on a merged requirements between cloudinary_js and your app (see [grunt lodash task](https://github.com/cloudinary/cloudinary_js/blob/118f5aa1f0bd912d770cd3bbf4740e8816b90baa/Gruntfile.coffee#L325-L346)) and use cloudinary-core with the special lodash build.

**Comment by yoadsn** [comment] 2017-12-04 06:40
@roeeba I wish there was a nice way to expose Cloudinary's part of the "merged requirements". So when the package is updated, and those dependencies change, we will not have to worry about missing anything. We can let the build tool take care of that.
I use webpack but this should apply to any modern bundler.

**Comment by ignatiusreza** [comment] 2017-12-04 07:39
The sample application was deliberately small, but, in a real application, the amount of duplication are non-trivial..

and even though it is possible to build custom script to further optimize cloudinary bundle on the client application, it seems like it would be best if cloudinary could fix the root cause by doing selective import, e.g. `import isEmpty from "lodash/isEmpty` vs `import _ from "lodash"`.. I can try to come up with a PR if you're open to the idea..

**Comment by tocker** [comment] 2017-12-21 13:40
The library was designed to be published as a single file - mainly for _backwards compatibility_.
Using "import ... from" is tricky because of the use of Coffee and the way our build is currently configured.
However you can get the list of functions the library is using with this command:

```
grep --only-matching -P '(_\.\w+)' 'src/util/lodash.coffee' | sort | uniq
```

This is how we build the shrikwrap version (as @roeeba mentioned [earlier](https://github.com/cloudinary/cloudinary_js/issues/114#issuecomment-348785437)). Crude but effective...

You can create a customised "ES6 module" build by replacing the UMD header in https://github.com/cloudinary/cloudinary_js/blob/118f5aa1f0bd912d770cd3bbf4740e8816b90baa/Gruntfile.coffee#L224-L242 with a list of imports based on https://github.com/cloudinary/cloudinary_js/blob/118f5aa1f0bd912d770cd3bbf4740e8816b90baa/Gruntfile.coffee#L326

Regardless, @ignatiusreza, PRs are always welcome! 😄 

---

FYI, we are planning to replace the lodash/jquery utils module with bespoke implementation which would resolve the dependency issue. In addition, we'll replace CoffeeScript with JS and Grunt with webpack at some point.

**Comment by ignatiusreza** [comment] 2017-12-29 06:24
That's great news! I can only imagine the amount of work require to fully migrate from CoffeeScript/Grunt to JS/webpack :sweat_smile: 

I've opened a PR at #136 meanwhile as an attempt to selectively require lodash.. to be honest, the amount of bytes saved is not as impressive as expected.. the final user build when doing selective import is smaller than importing all of lodash, but shrinkwrap version are somehow still smaller..

**Closed** 2018-02-05 13:22 UTC
Labels: question

**Comment by sakulstra** [comment] 2018-07-27 14:15
@tocker is there any updates on the es, non coffee-script version? Currently cloudinary is a pretty huge part of our application bundle.

**Comment by tocker** [comment] 2018-08-02 11:44
@sakulstra We are porting the code from CoffeeScript to JS.

**Comment by Dakkers** [comment] 2018-12-02 20:15
is there any progress on this? Cloudinary takes 11% of our bundle size, 66% of which is from Lodash.
